import { useState } from 'react'
import { Icon } from '../../dashboard/Icon'
import { card, SectionTitle, Toggle } from '../../posturesync/Shared'

export default function LaptopControlPage({ data }) {
  const [enabled, setEnabled] = useState(true)
  const [gesture, setGesture] = useState('Awaiting input...')
  return <div className="space-y-6"><section className={`${card} flex flex-col justify-between gap-4 md:flex-row md:items-center`}><div><p className="text-xs font-bold uppercase tracking-wider text-[#8eb69b]">Laptop control</p><h1 className="mt-1 text-2xl font-bold">Hands-free gestures</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#8eb69b]">Use subtle head and torso movements to navigate your laptop without reaching for the keyboard.</p></div><div className="flex items-center gap-3 rounded-xl bg-[#051f20] px-4 py-3"><span className="text-xs font-semibold">Gesture Control</span><Toggle enabled={enabled} onChange={setEnabled} /></div></section><div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className={card}><SectionTitle eyebrow="Active mappings" title="Your gesture shortcuts" /><div className="grid gap-4 sm:grid-cols-2">{data.gestures.map((item) => <div key={item.gesture} className="rounded-xl border border-[#235347] bg-[#051f20] p-4"><div className="flex items-center justify-between"><span className="rounded-lg bg-[#163832] p-2 text-[#8eb69b]"><Icon name={item.icon} size={18} /></span><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">Configured</span></div><p className="mt-4 text-sm font-bold">{item.gesture}</p><p className="mt-1 text-xs text-[#8eb69b]">→ {item.action}</p></div>)}</div></section><section className="space-y-6"><div className={card}><SectionTitle eyebrow="Configuration" title="Sensitivity" /><input type="range" min="0" max="100" defaultValue="54" className="w-full accent-[#8eb69b]" /><div className="mt-2 flex justify-between text-[11px] text-[#8eb69b]"><span>Subtle</span><span>Exaggerated</span></div><button type="button" className="mt-5 w-full rounded-xl bg-[#8eb69b] px-4 py-3 text-xs font-bold text-[#051f20]">Calibrate Sensors</button></div><div className={card}><SectionTitle eyebrow="Test area" title="Gesture preview" /><button type="button" onClick={() => setGesture(gesture === 'Awaiting input...' ? 'Head nod detected — Select / Click' : 'Awaiting input...')} className="flex h-32 w-full items-center justify-center rounded-xl border border-dashed border-[#8eb69b] bg-[#051f20] text-center text-sm text-[#8eb69b]">{gesture}</button><p className="mt-3 text-[11px] text-[#8eb69b]">Click the preview to simulate a sensor gesture.</p></div></section></div></div>
}
