import { useState } from 'react'
import { Icon } from '../../dashboard/Icon'
import { card, SectionTitle, StatTile } from '../../posturesync/Shared'

export default function AlertsPage({ data }) {
  const [filter, setFilter] = useState('All')
  const visible = filter === 'All' ? data.alerts : data.alerts.filter((alert) => alert.severity === filter.toLowerCase())
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-wider text-[#8eb69b]">Alerts</p><h1 className="mt-1 text-2xl font-bold">Posture alert history</h1><p className="mt-2 text-sm text-[#8eb69b]">Review reminders and corrections from your connected sensors.</p></div><div className="grid gap-6 md:grid-cols-3"><StatTile label="Alerts Today" value="3" detail="2 fewer than yesterday" icon="bell" /><StatTile label="Most Common" value="Head posture" detail="4 occurrences this week" icon="alert" tone="aware" /><StatTile label="Response Time" value="42s" detail="18% faster this week" icon="history" /></div><section className={card}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><SectionTitle eyebrow="Activity feed" title="Recent alerts" /><div className="flex gap-2">{['All', 'Aware', 'Poor', 'Bad'].map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${filter === item ? 'bg-[#8eb69b] text-[#051f20]' : 'bg-[#163832] text-[#8eb69b]'}`}>{item}</button>)}</div></div><div className="space-y-3">{visible.map((alert) => <div key={alert.id} className="flex items-start gap-4 rounded-xl border border-[#235347] bg-[#051f20] p-4"><span className={`rounded-xl p-2 ${alert.severity === 'bad' ? 'bg-red-400/10 text-red-400' : alert.severity === 'poor' ? 'bg-orange-400/10 text-orange-400' : 'bg-amber-300/10 text-amber-300'}`}><Icon name="alert" size={20} /></span><div className="flex-1"><div className="flex flex-col justify-between gap-1 sm:flex-row"><p className="font-bold">{alert.type}</p><time className="text-xs text-[#8eb69b]">{alert.time}</time></div><p className="mt-1 text-sm text-[#8eb69b]">{alert.description}</p></div></div>)}</div></section></div>
}
