// ------------------------- TAILWIND CONFIGURATION -------------------------
module.exports = {
  content: ['./src/index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        panel: 'rgb(var(--color-panel) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--color-accent-foreground) / <alpha-value>)',
        divider: 'rgb(var(--color-divider) / <alpha-value>)',
        navy: '#1C2D3A',
        slate: '#455A64',
        mauve: '#9B5E6D',
        offwhite: '#F0F2F5',
        'light-navy': '#1C2D3A',
        'light-slate': '#455A64',
        'light-rose': '#9B5E6D',
        'light-bg': '#F0F2F5',
        'dark-obsidian': '#0A060E',
        'dark-midnight': '#12111C',
        'dark-ink': '#1A131E',
        'dark-nocturne': '#251B28',
        'dark-text': '#F2EDE9',
        'dark-text-strong': '#FFFFFF',
        'dark-accent': '#C65F7D',
        brand: {
          plum: '#1C2D3A',
          teal: '#9B5E6D',
          sage: '#9B5E6D',
          cream: '#F0F2F5',
          navy: '#F0F2F5',
          surface: '#FFFFFF',
          panel: '#E7EBEF',
          border: '#455A64',
          cyan: '#9B5E6D',
          indigo: '#455A64',
          green: '#9B5E6D',
          yellow: '#9B5E6D',
          berry: '#9B5E6D',
          blue: '#455A64',
          'text-primary': '#1C2D3A',
          'text-secondary': '#455A64',
        },
        'status-good': '#22C55E',
        'status-warn': '#F59E0B',
        'status-bad': '#EF4444',
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #9B5E6D 0%, #9B5E6D 100%)',
      },
      fontFamily: {
        display: ['Baloo 2', 'ui-sans-serif', 'system-ui'],
        sans: ['Quicksand', 'Inter', 'Segoe UI', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
}
