import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import correctPosture from '../../../assets/postures/neutral_posture.jpg'
import { card, SectionTitle } from '../../posturesync/Shared'

const axes = [['neck_x', 'Neck X', '#8eb69b'], ['neck_y', 'Neck Y', '#fbbf24'], ['lumbar_x', 'Lumbar X', '#60a5fa'], ['lumbar_y', 'Lumbar Y', '#f472b6']]

function AxisChart({ axis, label, color, history }) {
  return <div className="flex min-h-0 min-w-0 flex-col rounded-xl border border-[#235347] bg-[#051f20] p-3"><p className="shrink-0 text-xs font-bold text-[#8eb69b]">{label}</p><div className="mt-2 min-h-0 min-w-0 flex-1">{history.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={history}><XAxis dataKey="time" hide /><YAxis hide domain={['auto', 'auto']} /><Tooltip contentStyle={{ background: '#163832', border: '1px solid #235347' }} /><Line type="monotone" dataKey={axis} stroke={color} dot={false} strokeWidth={1.5} /></LineChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-xs text-[#8eb69b]">Waiting for data...</div>}</div></div>
}

export default function LiveDataPage({ telemetry, history, classification, goodPosture }) {
  const updated = telemetry?.received_at || telemetry?.timestamp
  const statusLabel = goodPosture === null ? 'Waiting...' : goodPosture ? 'Good' : 'Needs Correction'
  const statusStyle = goodPosture === null ? 'live-status-waiting' : goodPosture ? 'live-status-good' : 'live-status-bad'
  return <div className="flex h-full min-h-0 flex-col gap-4 overflow-hidden"><div className="grid min-h-0 min-w-0 flex-[0_0_38%] gap-4 md:grid-cols-[minmax(240px,0.75fr)_minmax(0,1.25fr)]"><section className={`${card} flex min-h-0 min-w-0 items-center justify-center overflow-hidden p-4`}><img src={correctPosture} alt="Correct posture reference" className="h-full max-h-48 w-full object-contain" /></section><section className={`${card} min-h-0 min-w-0 overflow-hidden`}><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase tracking-wider text-[#8eb69b]">Live posture</p><h1 className="mt-1 truncate text-2xl font-bold">{classification?.label || ''}</h1><p className="mt-2 truncate text-sm text-[#8eb69b]">{updated ? `Updated ${new Date(updated).toLocaleTimeString()}` : ''}</p></div><span className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold ${statusStyle}`}>{statusLabel}</span></div><div className="mt-4 grid min-w-0 grid-cols-2 gap-2 sm:gap-3">{axes.map(([key, label]) => <div key={key} className="flex h-[76px] min-w-0 flex-col overflow-hidden rounded-xl border border-[#235347] bg-[#051f20] p-3"><p className="h-4 truncate text-xs leading-4 text-[#8eb69b]">{label}</p><p className="mt-2 flex h-6 items-center overflow-hidden text-ellipsis whitespace-nowrap text-lg font-bold">{Number.isFinite(telemetry?.[key]) ? telemetry[key].toFixed(2) : <span className="text-xs font-medium text-[#8eb69b]">Waiting for data...</span>}</p></div>)}</div></section></div><section className={`${card} flex min-h-0 min-w-0 flex-1 flex-col overflow-hidden`}><SectionTitle eyebrow="Rolling window" title="Sensor history" /><div className="grid min-h-0 min-w-0 flex-1 grid-cols-1 grid-rows-4 gap-3 sm:grid-cols-2 sm:grid-rows-2">{axes.map(([axis, label, color]) => <AxisChart key={axis} axis={axis} label={label} color={color} history={history} />)}</div></section></div>
}
