import { useState } from 'react'
import logoSrc from '../../assets/ispa-logo.png'

export default function LoginPage({ onLogin }) {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState('')
  const [darkMode, setDarkMode] = useState(true)
  function submit(event) { event.preventDefault(); if (username.trim() && password === 'admin') onLogin(username.trim()); else setError('Invalid username or password') }
  return <main className={`${darkMode ? 'theme-dark bg-brand-plum text-brand-plum' : 'theme-light bg-brand-cream text-brand-plum'} flex min-h-screen items-center justify-center p-5 transition-colors`}><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-brand-border bg-brand-surface p-8 shadow-2xl shadow-brand-plum/30"><div className="text-center"><img src={logoSrc} alt="ISPA" className="mx-auto h-20 w-48 rounded-xl object-contain" /><p className="mt-5 text-2xl font-bold">ISPA</p><p className="mt-1 text-sm text-brand-plum/70">Incorrect Posture Determination via Spine Alignment</p></div><div className="mt-8 space-y-4"><label className="block text-xs font-semibold text-brand-plum/75">Username<input placeholder="Username" value={username} onChange={(event) => setUsername(event.target.value)} className="mt-2 w-full rounded-xl border border-brand-border bg-brand-navy px-4 py-3 text-sm text-brand-plum placeholder:text-brand-plum/55 outline-none focus:border-brand-teal focus:ring-2 focus:ring-brand-teal/30" /></label><label className="block text-xs font-semibold text-brand-plum/75">Password<input placeholder="Password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-brand-border bg-brand-navy px-4 py-3 text-sm text-brand-plum placeholder:text-brand-plum/55 outline-none focus:border-brand-teal focus:ring-2 focus:ring-brand-teal/30" /></label></div>{error && <p className="mt-4 rounded-xl bg-red-400/10 px-3 py-2 text-xs font-semibold text-red-300">{error}</p>}<button type="submit" className="mt-6 w-full rounded-xl bg-brand-gradient px-4 py-3 text-sm font-bold text-brand-plum transition hover:brightness-110">Log In</button><button type="button" onClick={() => setDarkMode((value) => !value)} className="mt-4 w-full text-center text-xs text-brand-plum/70 hover:text-brand-teal">{darkMode ? 'Switch to light mode' : 'Switch to dark mode'}</button></form></main>
}
