import { useState } from 'react'
import logoSrc from '../../assets/ispa-logo.png'
import { Icon } from './Icon'
import NotificationCenter from './NotificationCenter'

const navigation = [['Home', 'dashboard'], ['Live Posture', 'live'], ['Connection', 'wifi'], ['Posture Almanac', 'book']]

export default function Sidebar({ activeTab, onNavigate, serialStatus, darkMode, onThemeChange }) {
  const [menuOpen, setMenuOpen] = useState(false)
  const state = serialStatus?.state || (serialStatus?.error ? 'error' : serialStatus?.listening ? 'connected' : 'disconnected')
  const navigate = (label) => { onNavigate(label === 'Connection' ? 'Device Connection' : label); setMenuOpen(false) }
  const active = (label) => activeTab === label || (label === 'Connection' && activeTab === 'Device Connection')
  return <aside className="relative z-20 px-3 pt-3 sm:px-6 lg:px-10 lg:pt-6">
    <div className="relative mx-auto flex w-full max-w-7xl items-center gap-3 rounded-3xl border border-offwhite/15 bg-navy px-3 py-2 text-offwhite shadow-[0_14px_30px_rgb(28_45_58_/_0.16)] sm:rounded-full">
      <div className="flex min-w-0 shrink-0 items-center px-1 sm:px-3"><img src={logoSrc} alt="I-SPA" className="logo-mark h-10 w-auto rounded-lg object-contain sm:h-11" /></div>
      <nav className="hidden min-w-0 flex-1 items-center justify-center gap-1 lg:flex">{navigation.map(([label, icon]) => <button key={label} type="button" onClick={() => navigate(label)} className={`group flex min-h-11 shrink-0 items-center gap-2 rounded-full px-3 py-2 text-xs font-semibold sm:px-4 sm:text-sm ${active(label) ? 'bg-mauve text-offwhite' : 'text-offwhite/70 hover:bg-offwhite/10 hover:text-offwhite'}`}><span className="hidden rounded-full bg-offwhite/10 p-1 sm:inline-flex"><Icon name={icon} size={15} strokeWidth={2.4} /></span><span className="whitespace-nowrap">{label}</span></button>)}</nav>
      <button type="button" onClick={() => setMenuOpen((open) => !open)} aria-expanded={menuOpen} aria-controls="mobile-navigation" aria-label={menuOpen ? 'Close navigation menu' : 'Open navigation menu'} className="ml-auto flex min-h-11 min-w-11 items-center justify-center rounded-full text-offwhite hover:bg-offwhite/10 lg:hidden"><Icon name={menuOpen ? 'chevron' : 'menu'} size={21} /></button>
      <div className="hidden shrink-0 items-center gap-1 border-l border-offwhite/20 pl-2 lg:flex"><button type="button" onClick={() => onThemeChange(!darkMode)} aria-pressed={darkMode} aria-label="Toggle light and dark theme" className="relative flex h-9 w-14 shrink-0 items-center rounded-full bg-offwhite/15 p-1"><span className={`flex h-7 w-7 items-center justify-center rounded-full bg-offwhite text-navy shadow-sm transition-transform duration-300 ${darkMode ? 'translate-x-5' : 'translate-x-0'}`}><Icon name={darkMode ? 'moon' : 'sun'} size={13} strokeWidth={2.5} /></span></button><NotificationCenter /><button type="button" onClick={() => navigate('Settings')} aria-label="Open Settings" title="Settings" className="flex h-10 w-10 items-center justify-center rounded-full text-offwhite/75 hover:bg-offwhite/10 hover:text-offwhite"><Icon name="settings" size={17} strokeWidth={2.4} /></button></div>
      {menuOpen && <><button type="button" aria-label="Close navigation menu" onClick={() => setMenuOpen(false)} className="fixed inset-0 z-40 bg-navy/30 lg:hidden" /><nav id="mobile-navigation" className="absolute left-0 right-0 top-full z-50 mt-2 flex max-h-[calc(100vh-5rem)] flex-col gap-1 overflow-y-auto rounded-2xl border border-offwhite/15 bg-navy p-3 shadow-2xl lg:hidden"><p className="px-3 pb-2 pt-1 text-[10px] font-bold uppercase tracking-[0.18em] text-offwhite/50">Navigation</p>{navigation.map(([label, icon]) => <button key={label} type="button" onClick={() => navigate(label)} className={`flex min-h-12 w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold ${active(label) ? 'bg-mauve text-offwhite' : 'text-offwhite/80 hover:bg-offwhite/10'}`}><Icon name={icon} size={18} />{label}</button>)}<div className="my-2 border-t border-offwhite/15" /><p className="px-3 pb-1 pt-1 text-[10px] font-bold uppercase tracking-[0.18em] text-offwhite/50">App controls</p><button type="button" onClick={() => onThemeChange(!darkMode)} aria-pressed={darkMode} className="flex min-h-12 w-full items-center justify-between rounded-xl px-4 py-3 text-left text-sm font-semibold text-offwhite/80 hover:bg-offwhite/10"><span className="flex items-center gap-3"><Icon name={darkMode ? 'moon' : 'sun'} size={18} />Theme</span><span className="rounded-full bg-offwhite/15 px-2 py-1 text-xs">{darkMode ? 'Dark' : 'Light'}</span></button><div className="flex min-h-12 items-center justify-between rounded-xl px-4 py-1 text-sm font-semibold text-offwhite/80"><span className="flex items-center gap-3"><Icon name="bell" size={18} />Notifications</span><NotificationCenter /></div><button type="button" onClick={() => navigate('Settings')} className="flex min-h-12 w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold text-offwhite/80 hover:bg-offwhite/10"><Icon name="settings" size={18} />Settings</button></nav></>}
    </div>
  </aside>
}
