// ------------------------- IMPORTS -------------------------
import logoSrc from '../../assets/ispa-logo.png'
import { Icon } from './Icon'
import NotificationCenter from './NotificationCenter'

// ------------------------- NAVIGATION CONFIGURATION -------------------------
const navigation = [['Home', 'dashboard'], ['Live Posture', 'live'], ['Connection', 'wifi'], ['Posture Almanac', 'book']]

// ------------------------- SIDEBAR COMPONENT -------------------------
export default function Sidebar({ activeTab, onNavigate, serialStatus, darkMode, onThemeChange }) {
  const state = serialStatus?.state || (serialStatus?.error ? 'error' : serialStatus?.listening ? 'connected' : 'disconnected')
  const stateLabel = { connected: 'Connected', connecting: 'Connecting', error: 'Error', disconnected: 'Disconnected' }[state] || 'Disconnected'
  const stateColor = { connected: 'bg-emerald-400', connecting: 'bg-amber-300', error: 'bg-red-400', disconnected: 'bg-slate-400' }[state] || 'bg-slate-400'
  return <aside className="relative z-20 px-4 pt-4 sm:px-6 lg:px-10 lg:pt-6"><div className="mx-auto flex w-full max-w-7xl items-center gap-3 rounded-full border border-offwhite/15 bg-navy px-3 py-2 text-offwhite shadow-[0_14px_30px_rgb(28_45_58_/_0.16)]"><div className="flex shrink-0 items-center gap-2 px-2"><img src={logoSrc} alt="I-SPA" className="logo-mark h-9 w-9 rounded-full border border-offwhite/60 bg-offwhite object-contain p-0.5" /><span className="hidden font-display text-lg font-bold sm:inline">I-SPA</span></div><nav className="flex min-w-0 flex-1 items-center justify-center gap-1 overflow-hidden">{navigation.map(([label, icon]) => <button key={label} type="button" onClick={() => onNavigate(label === 'Connection' ? 'Device Connection' : label)} className={`group flex shrink-0 items-center gap-2 rounded-full px-3 py-2 text-xs font-semibold transition duration-150 sm:px-4 sm:text-sm ${activeTab === label || (label === 'Connection' && activeTab === 'Device Connection') ? 'bg-mauve text-offwhite' : 'text-offwhite/70 hover:bg-offwhite/10 hover:text-offwhite'}`}><span className="hidden rounded-full bg-offwhite/10 p-1 group-hover:bg-offwhite/15 sm:inline-flex"><Icon name={icon} size={15} strokeWidth={2.4} /></span><span className="whitespace-nowrap">{label}</span></button>)}</nav><div className="ml-1 flex shrink-0 items-center gap-1 border-l border-offwhite/20 pl-2"><button type="button" onClick={() => onThemeChange(!darkMode)} aria-pressed={darkMode} aria-label="Toggle light and dark theme" title="Toggle light and dark theme" className="relative flex h-8 w-14 shrink-0 items-center rounded-full bg-offwhite/15 p-1 transition duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-mauve"><span className={`flex h-6 w-6 items-center justify-center rounded-full bg-offwhite text-navy shadow-sm transition-transform duration-300 ${darkMode ? 'translate-x-6' : 'translate-x-0'}`}><Icon name={darkMode ? 'moon' : 'sun'} size={13} strokeWidth={2.5} /></span></button><button type="button" onClick={() => onNavigate('Settings')} aria-label="Open Settings" title="Settings" className="flex h-9 w-9 items-center justify-center rounded-full text-offwhite/75 transition duration-150 hover:bg-offwhite/10 hover:text-offwhite focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-mauve"><Icon name="settings" size={17} strokeWidth={2.4} /></button></div></div></aside>
}
