import logoSrc from '../../assets/ispa-logo.png'
import { Icon } from './Icon'

const navigation = [['Dashboard', 'dashboard'], ['Live Data', 'live'], ['Live Monitoring', 'live'], ['Analytics', 'chart'], ['Posture Almanac', 'book'], ['Alerts', 'alert'], ['Device & Settings', 'settings']]

export default function Sidebar({ device, activeTab, onNavigate, user = {} }) {
  const displayName = user.name || 'Profile'
  return <aside className="flex w-full shrink-0 flex-col border-b border-[#235347] bg-[#0b2b26] px-5 py-5 text-[#daf1de] lg:fixed lg:inset-y-0 lg:left-0 lg:w-60 lg:border-b-0 lg:border-r lg:px-4"><div className="flex items-center gap-3 px-2"><img src={logoSrc} alt="ISPA" className="h-11 w-11 rounded-xl object-cover" /><div><p className="text-[15px] font-bold leading-tight">ISPA</p><p className="mt-1 text-[10px] text-[#8eb69b]">Spine alignment monitor</p></div></div><nav className="mt-7 grid grid-cols-3 gap-1 sm:grid-cols-6 lg:block lg:space-y-1">{navigation.map(([label, icon]) => <button key={label} type="button" onClick={() => onNavigate(label)} className={`flex w-full items-center justify-center gap-3 rounded-xl px-3 py-2.5 text-xs font-medium transition lg:justify-start ${activeTab === label ? 'bg-[#8eb69b] text-[#051f20]' : 'text-[#8eb69b] hover:bg-[#163832] hover:text-[#daf1de]'}`}><Icon name={icon} size={17} /><span className="hidden sm:inline">{label}</span></button>)}</nav><div className="mt-7 border-t border-[#235347] pt-5 lg:mt-auto"><div className="mb-4 rounded-xl border border-brand-border bg-brand-surface p-3 text-brand-primary"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${device.connected ? 'bg-emerald-400' : 'bg-slate-400'}`} /><p className="text-xs font-bold">{device.connected ? 'ESP32 receiving' : 'Waiting for ESP32'}</p></div><p className="mt-2 text-[11px] text-brand-secondary">{device.bluetooth}</p><button type="button" onClick={() => onNavigate('Connect ESP32')} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg border border-brand-teal px-3 py-2 text-[11px] font-semibold text-brand-primary hover:bg-brand-teal/20"><Icon name="wifi" size={14} />Connection</button></div><button type="button" onClick={() => onNavigate('Profile')} className={`flex w-full items-center gap-3 rounded-xl p-2 text-left transition hover:bg-[#163832] ${activeTab === 'Profile' ? 'bg-[#163832]' : ''}`}><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#8eb69b] text-xs font-bold text-[#051f20]">{displayName.slice(0, 2).toUpperCase()}</span><span><span className="block text-xs font-bold">{displayName}</span><span className="mt-1 block text-[10px] text-[#8eb69b]">Profile & preferences</span></span></button></div></aside>
}
