import { useState } from 'react'
import { Icon } from '../../dashboard/Icon'
import { card, SectionTitle, statusColors } from '../../posturesync/Shared'

function PostureImage({ image, imageName, name }) {
  const [failed, setFailed] = useState(false)
  if (failed) return <div className="flex h-40 items-center justify-center rounded-xl border border-dashed border-status-warn bg-brand-navy p-3 text-center text-xs text-status-warn">Missing image: {imageName}</div>
  return <div className="flex h-40 items-center justify-center rounded-xl border border-brand-border bg-brand-navy p-3"><img src={image} alt={`${name} posture`} onError={() => setFailed(true)} className="max-h-36 max-w-full rounded-lg object-contain" /></div>
}

export default function PostureAlmanacPage({ data }) {
  return <div className="space-y-6"><div className="relative overflow-hidden rounded-3xl border border-brand-border bg-brand-surface p-6"><div className="absolute -right-10 -top-16 h-44 w-44 rotate-45 bg-brand-gradient opacity-20" /><p className="relative text-xs font-bold uppercase tracking-[0.2em] text-brand-yellow">Field guide · 01—08</p><h1 className="relative mt-2 text-3xl font-bold">Posture Almanac</h1><p className="relative mt-2 max-w-2xl text-sm leading-6 text-slate-400">A visual reference for the eight alignment states recognized by the PostureGuard sensor model.</p></div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.postureAlmanac.map((item, index) => <article key={item.logic} className={`${card} overflow-hidden ${index % 3 === 0 ? 'rounded-tl-[2.5rem]' : index % 3 === 1 ? 'rounded-br-[2.5rem]' : ''}`}><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-slate-500">ENTRY {String(index + 1).padStart(2, '0')}</span><span className={`text-xs font-bold ${statusColors[item.tone]}`}>● {item.tone}</span></div><div className="mt-3"><PostureImage image={item.image} imageName={item.imageName} name={item.name} /></div><h2 className="mt-4 text-lg font-bold">{item.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-400">{item.description}</p><code className="mt-4 inline-flex rounded-lg border border-brand-border bg-brand-navy px-2.5 py-1.5 text-[11px] text-brand-yellow">{item.logic}</code></article>)}</div><section className={card}><SectionTitle eyebrow="Sensor reference" title="Angle definitions & thresholds" action={<Icon name="book" size={22} />} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['Neck Pitch', 'Forward / backward head angle'], ['Lumbar Pitch', 'Lower-back forward curve'], ['Neck Roll', 'Side-to-side head tilt'], ['Lumbar Roll', 'Side-to-side hip tilt']].map(([label, detail]) => <div key={label} className="rounded-xl border border-brand-border bg-brand-navy p-4"><p className="text-sm font-bold">{label}</p><p className="mt-1 text-xs text-slate-400">{detail}</p></div>)}</div><div className="mt-5 grid gap-3 text-xs sm:grid-cols-3"><div className="rounded-xl border-l-4 border-status-good bg-status-good/10 p-3"><b className="text-status-good">Good</b><p className="mt-1 text-slate-400">Pitch 0°–18° · Roll 0°–8°</p></div><div className="rounded-xl border-l-4 border-status-warn bg-status-warn/10 p-3"><b className="text-status-warn">Warning</b><p className="mt-1 text-slate-400">Pitch 18°–30° · Roll 8°–15°</p></div><div className="rounded-xl border-l-4 border-status-bad bg-status-bad/10 p-3"><b className="text-status-bad">Bad</b><p className="mt-1 text-slate-400">Pitch &gt;30° · Roll &gt;15°</p></div></div></section></div>
}
